/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as MatchesNewRouteImport } from './routes/matches/new'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as MatchesIdScoreRouteImport } from './routes/matches/$id.score'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdScoreRoute = MatchesIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => MatchesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/matches/': typeof MatchesIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/matches': typeof MatchesIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/players': typeof PlayersRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/matches/': typeof MatchesIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/friends'
    | '/players'
    | '/profile'
    | '/teams'
    | '/matches/$id'
    | '/matches/new'
    | '/matches/'
    | '/matches/$id/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/friends'
    | '/players'
    | '/profile'
    | '/teams'
    | '/matches/$id'
    | '/matches/new'
    | '/matches'
    | '/matches/$id/score'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/friends'
    | '/players'
    | '/profile'
    | '/teams'
    | '/matches/$id'
    | '/matches/new'
    | '/matches/'
    | '/matches/$id/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRoute
  PlayersRoute: typeof PlayersRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRoute
  MatchesIdRoute: typeof MatchesIdRouteWithChildren
  MatchesNewRoute: typeof MatchesNewRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id/score': {
      id: '/matches/$id/score'
      path: '/score'
      fullPath: '/matches/$id/score'
      preLoaderRoute: typeof MatchesIdScoreRouteImport
      parentRoute: typeof MatchesIdRoute
    }
  }
}

interface MatchesIdRouteChildren {
  MatchesIdScoreRoute: typeof MatchesIdScoreRoute
}

const MatchesIdRouteChildren: MatchesIdRouteChildren = {
  MatchesIdScoreRoute: MatchesIdScoreRoute,
}

const MatchesIdRouteWithChildren = MatchesIdRoute._addFileChildren(
  MatchesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRoute,
  PlayersRoute: PlayersRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRoute,
  MatchesIdRoute: MatchesIdRouteWithChildren,
  MatchesNewRoute: MatchesNewRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
