/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as MigrationImportRouteImport } from './routes/migration-import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as BackupCenterRouteImport } from './routes/backup-center'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlayersRankingsRouteImport } from './routes/players.rankings'
import { Route as PlayersNewRouteImport } from './routes/players.new'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as MatchesNewRouteImport } from './routes/matches/new'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as MatchesIdIndexRouteImport } from './routes/matches/$id.index'
import { Route as MatchesIdScoreRouteImport } from './routes/matches/$id.score'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationImportRoute = MigrationImportRouteImport.update({
  id: '/migration-import',
  path: '/migration-import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupCenterRoute = BackupCenterRouteImport.update({
  id: '/backup-center',
  path: '/backup-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRankingsRoute = PlayersRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => PlayersRoute,
} as any)
const PlayersNewRoute = PlayersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PlayersRoute,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlayersRoute,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/matches/new',
  path: '/matches/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdIndexRoute = MatchesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesIdRoute,
} as any)
const MatchesIdScoreRoute = MatchesIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => MatchesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup-center': typeof BackupCenterRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/migration-import': typeof MigrationImportRoute
  '/players': typeof PlayersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/new': typeof PlayersNewRoute
  '/players/rankings': typeof PlayersRankingsRoute
  '/admin/': typeof AdminIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
  '/matches/$id/': typeof MatchesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup-center': typeof BackupCenterRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/migration-import': typeof MigrationImportRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/new': typeof PlayersNewRoute
  '/players/rankings': typeof PlayersRankingsRoute
  '/admin': typeof AdminIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
  '/matches/$id': typeof MatchesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup-center': typeof BackupCenterRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/migration-import': typeof MigrationImportRoute
  '/players': typeof PlayersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/teams': typeof TeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/matches/$id': typeof MatchesIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/new': typeof PlayersNewRoute
  '/players/rankings': typeof PlayersRankingsRoute
  '/admin/': typeof AdminIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/matches/$id/score': typeof MatchesIdScoreRoute
  '/matches/$id/': typeof MatchesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup-center'
    | '/change-password'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/migration-import'
    | '/players'
    | '/profile'
    | '/register'
    | '/setup'
    | '/teams'
    | '/admin/users'
    | '/matches/$id'
    | '/matches/new'
    | '/players/$id'
    | '/players/new'
    | '/players/rankings'
    | '/admin/'
    | '/matches/'
    | '/players/'
    | '/matches/$id/score'
    | '/matches/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup-center'
    | '/change-password'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/migration-import'
    | '/profile'
    | '/register'
    | '/setup'
    | '/teams'
    | '/admin/users'
    | '/matches/new'
    | '/players/$id'
    | '/players/new'
    | '/players/rankings'
    | '/admin'
    | '/matches'
    | '/players'
    | '/matches/$id/score'
    | '/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/backup-center'
    | '/change-password'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/migration-import'
    | '/players'
    | '/profile'
    | '/register'
    | '/setup'
    | '/teams'
    | '/admin/users'
    | '/matches/$id'
    | '/matches/new'
    | '/players/$id'
    | '/players/new'
    | '/players/rankings'
    | '/admin/'
    | '/matches/'
    | '/players/'
    | '/matches/$id/score'
    | '/matches/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupCenterRoute: typeof BackupCenterRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  MigrationImportRoute: typeof MigrationImportRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  TeamsRoute: typeof TeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MatchesIdRoute: typeof MatchesIdRouteWithChildren
  MatchesNewRoute: typeof MatchesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration-import': {
      id: '/migration-import'
      path: '/migration-import'
      fullPath: '/migration-import'
      preLoaderRoute: typeof MigrationImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup-center': {
      id: '/backup-center'
      path: '/backup-center'
      fullPath: '/backup-center'
      preLoaderRoute: typeof BackupCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/rankings': {
      id: '/players/rankings'
      path: '/rankings'
      fullPath: '/players/rankings'
      preLoaderRoute: typeof PlayersRankingsRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/players/new': {
      id: '/players/new'
      path: '/new'
      fullPath: '/players/new'
      preLoaderRoute: typeof PlayersNewRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/matches/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id/': {
      id: '/matches/$id/'
      path: '/'
      fullPath: '/matches/$id/'
      preLoaderRoute: typeof MatchesIdIndexRouteImport
      parentRoute: typeof MatchesIdRoute
    }
    '/matches/$id/score': {
      id: '/matches/$id/score'
      path: '/score'
      fullPath: '/matches/$id/score'
      preLoaderRoute: typeof MatchesIdScoreRouteImport
      parentRoute: typeof MatchesIdRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersNewRoute: typeof PlayersNewRoute
  PlayersRankingsRoute: typeof PlayersRankingsRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersIdRoute: PlayersIdRoute,
  PlayersNewRoute: PlayersNewRoute,
  PlayersRankingsRoute: PlayersRankingsRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

interface MatchesIdRouteChildren {
  MatchesIdScoreRoute: typeof MatchesIdScoreRoute
  MatchesIdIndexRoute: typeof MatchesIdIndexRoute
}

const MatchesIdRouteChildren: MatchesIdRouteChildren = {
  MatchesIdScoreRoute: MatchesIdScoreRoute,
  MatchesIdIndexRoute: MatchesIdIndexRoute,
}

const MatchesIdRouteWithChildren = MatchesIdRoute._addFileChildren(
  MatchesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupCenterRoute: BackupCenterRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  MigrationImportRoute: MigrationImportRoute,
  PlayersRoute: PlayersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  TeamsRoute: TeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  MatchesIdRoute: MatchesIdRouteWithChildren,
  MatchesNewRoute: MatchesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
